services:
  ui:
    image: ghcr.io/gibsongodsan/socialclubs-fe:latest
    depends_on:
      - api
    networks:
      - socialclubs-network
    command: npm start

  api:
    build: ghcr.io/gibsongodsan/socialclubs-be:latest
    depends_on:
      - db
    networks:
      - socialclubs-network
    env_file:
      - ./env/backend.env
    restart: always
    command:
      [
        "/bin/sh",
        "-c",
        "python manage.py migrate && python manage.py runserver 0.0.0.0:8000",
      ]

  db:
    image: postgres:latest
    env_file:
      - ./env/db.env
    volumes:
      - socialclubs-pgdata:/var/lib/postgresql/data
    networks:
      - socialclubs-network

  nginx:
    image: ghcr.io/gibsongodsan/socialclubs-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - ui
      - api
    restart: always
    networks:
      - socialclubs-network

volumes:
  socialclubs-pgdata:

networks:
  socialclubs-network:
    driver: bridge
